minimumReleaseAgeExclude:
  - '@unocss/cli@66.10.1'
  - '@unocss/config@66.10.1'
  - '@unocss/core@66.10.1'
  - '@unocss/eslint-config@66.10.1'
  - '@unocss/eslint-plugin@66.10.1'
  - '@unocss/extractor-arbitrary-variants@66.10.1'
  - '@unocss/inspector@66.10.1'
  - '@unocss/preset-attributify@66.10.1'
  - '@unocss/preset-icons@66.10.1'
  - '@unocss/preset-mini@66.10.1'
  - '@unocss/preset-tagify@66.10.1'
  - '@unocss/preset-typography@66.10.1'
  - '@unocss/preset-uno@66.10.1'
  - '@unocss/preset-web-fonts@66.10.1'
  - '@unocss/preset-wind3@66.10.1'
  - '@unocss/preset-wind4@66.10.1'
  - '@unocss/preset-wind@66.10.1'
  - '@unocss/rollup@66.10.1'
  - '@unocss/rule-utils@66.10.1'
  - '@unocss/transformer-attributify-jsx@66.10.1'
  - '@unocss/transformer-compile-class@66.10.1'
  - '@unocss/transformer-directives@66.10.1'
  - '@unocss/transformer-variant-group@66.10.1'
  - '@unocss/vite@66.10.1'
  - '@unocss/webpack@66.10.1'
  - unocss@66.10.1
  - unocss-applet@0.15.0
  - '@unocss-applet/preset-applet@0.15.0'
  - '@unocss-applet/preset-rem-rpx@0.15.0'
  - '@unocss-applet/transformer-attributify@0.15.0'
  - '@unocss-applet/transformer-hover@0.15.0'
  - '@unocss/preset-legacy-compat@66.10.1'

shellEmulator: true

trustPolicy: off

packages:
  - playground

catalogs:
  eslint:
    '@uni-helper/eslint-config': ^0.7.5
    eslint: ^10.10.0
  types:
    '@types/node': ^26.5.0
  typescript:
    typescript: ^6.0.3
  uni-app:
    '@dcloudio/types': ^3.4.32
    '@dcloudio/uni-app': 3.0.0-5000720260410001
    '@dcloudio/uni-app-plus': 3.0.0-5000720260410001
    '@dcloudio/uni-automator': 3.0.0-5000720260410001
    '@dcloudio/uni-cli-shared': 3.0.0-5000720260410001
    '@dcloudio/uni-components': 3.0.0-5000720260410001
    '@dcloudio/uni-h5': 3.0.0-5000720260410001
    '@dcloudio/uni-mp-alipay': 3.0.0-5000720260410001
    '@dcloudio/uni-mp-baidu': 3.0.0-5000720260410001
    '@dcloudio/uni-mp-jd': 3.0.0-5000720260410001
    '@dcloudio/uni-mp-kuaishou': 3.0.0-5000720260410001
    '@dcloudio/uni-mp-lark': 3.0.0-5000720260410001
    '@dcloudio/uni-mp-qq': 3.0.0-5000720260410001
    '@dcloudio/uni-mp-toutiao': 3.0.0-5000720260410001
    '@dcloudio/uni-mp-weixin': 3.0.0-5000720260410001
    '@dcloudio/uni-mp-xhs': 3.0.0-5000720260410001
    '@dcloudio/uni-quickapp-webview': 3.0.0-5000720260410001
    '@dcloudio/uni-stacktracey': 3.0.0-5000720260410001
    '@dcloudio/vite-plugin-uni': 3.0.0-5000720260410001
    '@iconify-json/carbon': ^1.2.26
    '@uni-helper/plugin-uni': ^0.1.0
    '@uni-helper/uni-app-types': ^1.1.0
    '@uni-helper/uni-env': ^0.3.1
    '@vue/tsconfig': ^0.9.1
    vue: ~3.4.38
    vue-i18n: ^9.13.1
    vue-tsc: ^3.3.11
  unocss:
    '@unocss/core': ~66.10.1
    '@unocss/eslint-config': ~66.10.1
    '@unocss/preset-legacy-compat': ~66.10.1
    '@unocss/preset-mini': ~66.10.1
    '@unocss/rule-utils': ~66.10.1
    unocss: ~66.10.1
    unocss-applet: ^0.15.0
  utils:
    bumpp: ^12.3.0
    tsdown: ^0.23.0
  vite:
    vite: ^5.4.21
    vitest: ^3.2.7

configDependencies:
  '@pnpm/plugin-trusted-deps': ^0.2.2

allowBuilds:
  core-js: true
  core-js-pure: true
  esbuild: true
